### ISSUE TITLE
Clickable icons to toggle collapsing

### ISSUE THREAD

**Issue by StevenLaan** [aquirdTurtle/Collapsible_Headings#1]
It would be nice to have buttons to click to toggle the collapsible headings.

In order to not pollute the discussion in the jupyterlab comments, I thought it would be better to raise an issue here to discuss this particular implementation (see: https://github.com/jupyterlab/jupyterlab/issues/2275#issuecomment-515885988)  

The InputArea.promptNode contains the HTML node to the left of the title. A div could be added that contains the button.

In order to add these buttons to every header that is added, the widgetAdded and currentChanged signals from the NotebookTracker need to be handled.

**Comment by aquirdTurtle** [comment]
Ah, this is a great start. Thanks for the pull request! I think in the end the button can both be clickable and indicate the collapsed status of the cell, similar to the original notebook extension. I'm thinking of something a little more minimalistic than the original default icon, maybe something like a ">" symbol for closed and "v" symbol for open.

**Comment by StevenLaan** [comment]
Yes, that's kind of the same thing I now implemented using the carets. I think the state of the master branch right now is enough for the first version of the toggle buttons. Therefore I'm closing the issue 😄 

There is room for improvement, but for me its working fine.
