### ISSUE TITLE
Compatibility problems with later jupyterlab versions.

### ISSUE THREAD

**Issue by picatoro** [aquirdTurtle/Collapsible_Headings#11]
Hello,
I would like to use this wonderful extension, but when I follow the installation instructions, the following message appears:

```
~$ jupyter labextension install @aquirdturtle/collapsible_headings
Node v12.12.0

> ~/anaconda3/envs/py/bin/npm pack @aquirdturtle/collapsible_headings
npm notice 
npm notice 📦  @aquirdturtle/collapsible_headings@0.5.0
...                                   
Errored, use --debug for full output:
ValueError: No version of @aquirdturtle/collapsible_headings could be found that is compatible with the current version of JupyterLab. However, it seems to support a new version of JupyterLab. Consider upgrading JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.19.1 <0.20.0        >=1.0.2 <2.0.0   @jupyterlab/application
>=0.19.1 <0.20.0        >=1.0.2 <2.0.0   @jupyterlab/apputils
>=0.19.2 <0.20.0        >=1.0.2 <2.0.0   @jupyterlab/notebook
```
My current version of jupyterlab is:
jupyterlab                0.35.6                   py37_0    conda-forge

Is there a way to make it work? 

Thank you!

**Comment by aquirdTurtle** [comment]
Hello, it looks like you are using a version of Jupyterlab that is about 6 months old, and I made the extension more recently. Can you upgrade Jupyterlab? The command would be `conda update jupyerlab`

**Comment by picatoro** [comment]
Hello, thanks a lot for the response. I upgraded and works very well.

My bad for the stupid question, I saw the requirement >=0.19.1 <0.20.0 and my version as higher and made the wrong assumption.

Thanks again!
