### ISSUE TITLE
LINKS on headings not working

### ISSUE THREAD

**Issue by JaviFLATIRON** [aquirdTurtle/Collapsible_Headings#15]
The extension disables the links on the headings. Example:
`# EXIT TICKET [HERE](https://forms.gle/...)`
`HERE` won't be displayed as a link and clicking on it won't have any effect.

**Comment by aquirdTurtle** [comment]
Hi @JaviFLATIRON, I didn't do anything which I think would affect this, but can't repeat this issue. Perhaps something related to Jupyterlab 2.0.0 fixed it. Can you upgrade to the latest version and see if that fixes the problem?

**Comment by JaviFLATIRON** [comment]
Thanks, @aquirdTurtle that fixed it
