### ISSUE TITLE
Write only "collapsed: true" metadata, skip "collapsed: false"

### ISSUE THREAD

**Issue by nanoant** [aquirdTurtle/Collapsible_Headings#17]
As in the title. It would be great if Collapsible_Headings would be transparent, so if I don't collapse anything and Open/Save notebook it is no different that one without extension installed, nothing extra added.

Additional reasoning is that I don't see much (information-wise) difference between having `"collapsed": false` and not having anything at all.

Also, I'd small suggestion to use lower case `"collapsed": true` instead of `"Collapsed": true`, as the other tags in the notebook are lowercase.

**Comment by aquirdTurtle** [comment]
Hi there @nanoant, thanks for the suggestions. Should work this way in just-published extension version 2.1.0.

**Comment by nanoant** [comment]
@aquirdTurtle Awesome, thank you.
