### ISSUE TITLE
Jupyterlab 2.0 compatibility 

### ISSUE THREAD

**Issue by harper357** [aquirdTurtle/Collapsible_Headings#19]
Jupyterlab just updated to 2.0. Collapsible_Headings no longer works. Here is the [migration guide ](https://jupyterlab.readthedocs.io/en/stable/developer/extension_migration.html#extension-migration)

**Comment by snakers4** [comment]
Tried to upgrade our environment to lab from notebook several times
Collapsible headings was the only thing remaining
Tried it today, faced the same error

**Comment by CRISPserver** [comment]
+1

**Comment by harper357** [comment]
#21

**Comment by aquirdTurtle** [comment]
Sorry for the delay, finally got a bit of time to breath. Just published extension version 2.0.0, should solve compatibility issues. Let me know if there are any problems.

**Comment by snakers4** [comment]
it works!
