### ISSUE TITLE
The extension does not work together with @jupyterlab/toc

### ISSUE THREAD

**Issue by hseara** [aquirdTurtle/Collapsible_Headings#23]
The extension does not work when @jupyterlab/toc is installed and enabled.

**Comment by aquirdTurtle** [comment]
Hi @hseara, Can you elaborate? It seems to work for me - both in my extension-development environment and my main work environment.

**Comment by hseara** [comment]
When jupyterlab/toc is installed this is what I get:

![image](https://user-images.githubusercontent.com/2016887/77121001-7a41c700-6a3a-11ea-8e10-9d2dcc47684d.png)

**Comment by aquirdTurtle** [comment]
Okay, a couple questions: do the shortcuts work? I.e. is just the buttons icons that are missing or is all functionality missing? What versions of the extensions & jupyterlab are you using? Maybe try `jupyter labextension update --all` and `conda update --all` if you haven't already?

**Comment by hseara** [comment]
Yes, my system is fully updated:

-  jupyterlab: v2.0.1
-  @aquirdturtle/collapsible_headings v2.2.0  enabled  OK

When I install my environment without `@jupyterlab/toc` then I find the expected functionality of the program (Visuals and bindings):

![image](https://user-images.githubusercontent.com/2016887/77145671-7e490580-6a89-11ea-8c52-c413e94ce221.png)

> :warning: Instructions of the installation procedure are contained in the picture

Once I install `@jupyterlab/toc` the functionality is gone, as shown in my original post. I now realized that `@jupyterlab/toc` partially incorporates the same functionality using its submenu:

![image](https://user-images.githubusercontent.com/2016887/77146475-65d9ea80-6a8b-11ea-95c8-c8b06e063f4a.png)

Please notice the arrows next to the captions in the submenu that can be used to collapse and expand code sections. It could be nice if the functionality of both extensions could work simultaneously.
 
> :warning: Once I install `@jupyterlab/toc` it is not enough with uninstalling it to get back the functionality of  `@aquirdturtle/collapsible_headings`. I need a new environment.

Please let me know if you need more help/details.

**Comment by aquirdTurtle** [comment]
Unfortunately even with your nice environment setup instructs I am not able to repeat the issue - both extensions still seem to work fine for me. I did notice that if I follow these instructions exactly I end up with jupyterlab version 1.2.6 since the 2.0 version is only on conda-forge atm but I don't see any issues with either. Can you open the javascipt console on your browser (f12 in chrome) and see if there are any conspicuous messages? The recent version should be quiet (although maybe I could make being quiet just the default option in a future release...) but you might be able to see if things are completely failing to load or crashing badly.

**Comment by aquirdTurtle** [comment]
I should mention that I don't know what the first line "`$goconda` was supposed to do.

**Comment by hseara** [comment]
First, ignore the  `goconda` command. It just initializes the conda environment that is not active by default. I like to have the default system python for system operations.

Second, I have reinstalled everything based on miniconda version: 4.8.2. I have deleted the priority for the conda-forge channel that previously I had:
`cat ~/.condarc`
```
channels:
  - conda-forge
  - defaults
```
(The file now does not exist)


Also, I am now using python 3.8. This are the installation instructions  for my environment:
```
conda create --name martini3 python=3.8
conda activate martini3
conda install numpy scipy networkx setuptools pbr sphinx
conda install -c conda-forge sphinxcontrib-apidoc
conda install -c conda-forge jupyterlab
jupyter labextension install @jupytelab/toc
jupyter labextension install @aquirdturtle/collapsible_headings
jupyter-lab
```
With these settings both packages now work together:

![image](https://user-images.githubusercontent.com/2016887/77253837-6629df80-6c5d-11ea-9fcb-96fe35531326.png)

There are some usability issues due to overlapped functionality. Namely, if I collapse a heading using the toc panel, then expanding it using the arrow next to the heading results in the only momentaneous expansion. Meaning, it collapses after a second alone. There are also similar issues when simultaneously working with the menu and your plugging arrows. Please notice in the attached image that for the first heading the arrow in toc menu points different that next to the heading itself. It will be awesome that the two plugins could be in sync. Meaning. If I expand on the menu, the same is true for the arrow of your package.

Therefore, now the two extension work (the problem might be the conda-source priority channel in my previous setup), though there are some syncing issues.

**Comment by harper357** [comment]
For what it is worth, I was having this issue, and finally "solved" it by doing a complete uninstall of Jupyter and reinstall. This involved looking at `jupyter --paths` to find where Jupyter put things, 'rm -rf' all those locations and running `pip3 uninstall jupyterlab` multiple times to make sure all old versions were uninstalled. This might have been overkill, but I was having some other issues with Jupyterlab 3 and this was fixed in trying to clear that up.

**Comment by aquirdTurtle** [comment]
Hi @harper357, not sure if this might be part of the issue, but the @jupyterlab/toc is now included in the main jupyterlab 3.0 installation and so it should not be necessary to install the extension anymore. I still haven't gotten around to trying to properly synchronize the opening/closing of headers in the toc and notebook.

**Comment by harper357** [comment]
That was actually the issue I was having that prompted me to do this complete uninstall. I uninstalled the old @jupyterlab/toc but then couldn't get the ToC tab to show back up in Jupyterlab 3.0. 

Now that I look at it, it looks like I am still seeing a sync issue (ToC doesn't open/close folds, but if I click on a subheader it will open to that). That is pretty minor for me as Collapsible Headings is fully functional. 

I'm happy to delete my previous (and this) comment if you don't think it is the right place for them.

**Comment by aquirdTurtle** [comment]
The TOC and this extension should now sync thanks to https://github.com/aquirdTurtle/Collapsible_Headings/pull/35
