### ISSUE TITLE
Collapsed headings do not persist after reopening a notebook

### ISSUE THREAD

**Issue by Lgcsimoes** [aquirdTurtle/Collapsible_Headings#24]
Hello! I am not sure if I am missing something, however the collapsed headings do not persist after closing a saved notebook and reopening again. This behaviour worked very well for the Jupyter Notebook extension, however this JupyterLab extension does not behave as I expected.

Am I missing any configuration, or could you include in capability in the future?
Thanks!

**Comment by DanXu-git** [comment]
I have the same problem.

**Comment by Lgcsimoes** [comment]
@aquirdTurtle , I was taking a look at the code, it seems that you set the `cell.metadata.collapsed = true`, but this same metadata is used by Jupyter Lab for output collapsing. For instance, the Jupyter Notebook collapsible_headings extension defines `cell.metadata.heading_collapsed = true`, avoiding using the same metadata as for output collapsing.

Do you think this could be the cause of this issue? Thanks!

**Comment by yongrenjie** [comment]
@Lgcsimoes's suggestion seems to work quite well - I have opened a PR if you think that is an acceptable fix.

**Comment by Babber** [comment]
Hey All,
it's not working for me. I have the updated version including the above fix, but it still only adds and removes the `"collapsed": "true"` piece of metadata and it opens all the headings expanded after re-loading the notebook. A working fix would be very much appreciated!

**Comment by aquirdTurtle** [comment]
Sorry this took me forever, I meant to immediately merge this but somehow slipped my notice that I hadn't actually done so. In any case, this is incorporated into release 2.3.0 which should now be available. Let me know if there are any further issues!

**Comment by Lgcsimoes** [comment]
Thanks, @aquirdTurtle!

Anyway, I have run the following command and now the collapsing icons no longer appear close to the title cells (and the keyboard shortcuts don't work either to collapse cells). The Extension Manager in Jupyter Lab says that your extension is updated and enabled. Am I doing something wrong to upgrade to 2.3.0?

`jupyter labextension update @aquirdturtle/collapsible_headings`

**Comment by aquirdTurtle** [comment]
Hi @Lgcsimoes, this sounds strange You're saying that the collapsing icons appear, but not close to the title cells? And none of the keyboard shortcuts work, not even the left or right arrows?  Can you do `jupyter labextension list` to check the current version? For me this looks like
```
PS C:\Users\Mark O. Brown\Code\Data-Analysis-Code> jupyter labextension list
JupyterLab v2.2.9
Known labextensions:
   app dir: C:\ProgramData\Miniconda3\share\jupyter\lab
        @aquirdturtle/collapsible_headings v2.3.0 enabled  ok
        @jupyterlab/latex v2.0.1 enabled  ok
        @jupyterlab/toc v4.0.0 enabled  ok
        jupyter-matplotlib v0.7.4 enabled  ok
```
What version of jupyter lab are you using? (`jupyter lab --version`)? If nothing looks particularly suspicious, you might try `conda update --all` if you are using conda as your package manager.

**Comment by Lgcsimoes** [comment]
Well, not quite what you said. The collapsing icons do not appear anywhere, and the keyboard shortcuts do not work either (left arrow, for instance). I have already performed the `conda update --all`. Here goes the output from the commands you requested (it is certainly weird that this extension is in the "Uninstalled core extensions" list):

`$ jupyter labextension list
JupyterLab v2.2.6
Known labextensions:
   app dir: /home/doug/anaconda3/share/jupyter/lab
        @aquirdturtle/collapsible_headings v2.3.0  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/toc v4.0.0  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK

Uninstalled core extensions:
    @aquirdturtle/collapsible_headings

$ jupyter lab --version
2.2.6`

**Comment by yongrenjie** [comment]
@Lgcsimoes Re. the extension appearing twice, https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688 as well as https://github.com/jupyterlab/jupyterlab/issues/8122 might be useful. I used to run into this issue all the time. For me the file I needed to delete was `~/Library/Python/3.8/share/jupyter/lab/settings/build_config.json`.

Afraid I can't help much beyond that though, sorry – I moved away from JupyterLab a while ago (not long after submitting that PR, in fact 😅)

**Comment by Lgcsimoes** [comment]
Great, @yongrenjie, deleting build_config.json worked perfectly! After posting this, I tried googling that error and I also stumbled upon this fix.
BTW, collapsible headings are indeed persisting now, thank you both!
