### ISSUE TITLE
Left/right arrows to navigate to the beginning/End of section

### ISSUE THREAD

**Issue by vrodriguezf** [aquirdTurtle/Collapsible_Headings#25]
Hi,

One feature that I use a lot in classic Jupyter notebooks with the collapsible heading extension is to navigate through he section with the left/right arrows. The collapse/uncollapse action of the arrows is only done when the cursor is focused on a header cell.

Is there anyway to do this in Jupyterlab with this extension?

Thanks!

**Comment by aquirdTurtle** [comment]
Hi @vrodriguezf, took me a while, but in now-published version 2.3.0 the collapsing/uncollapsing behavior should be identical to that of the old jupyter notebook extension. Let me know if there are any more issues!

**Comment by vrodriguezf** [comment]
works like a charm! Thank you!!!
