### ISSUE TITLE
Cannot get extension to work

### ISSUE THREAD

**Issue by erik-rossbach** [aquirdTurtle/Collapsible_Headings#29]
**JupyterLab v2.2.6**
**@aquirdturtle/collapsible_headings v 2.2.0 enabled OK**

Hello, 
for some reason the extension does not work.

I cannot see the buttons to collapse, nor use the keyboard shortcuts.

![image](https://user-images.githubusercontent.com/67185930/102104438-7a86bb80-3e2e-11eb-8f81-c0bf0e387128.png)

I would really like to use this extension. What could I be doing wrong?

Thank you in advance for your help

**Comment by aquirdTurtle** [comment]
Hi riktross, I'm not immediately sure what the issue might be, so a couple of debugging steps are in order.

- Are you using any unusual other extensions which might mess with the behavior of the notebook? if so, maybe try uninstalling those to see if they are contributing to the problem. 
- Can you open the javascript debugger for your web browser (usually f12), look at the console output, and see if you see any suspicious errors that might point us to the problem? 
- If no hints from here, try making a new bare-bones environment (e.g. with just conda) with just jupyterlab and my extension to see if it works there.

Once we figure out what's causing the issue, hopefully I can repeat it on my end and then find a solution.

**Comment by aquirdTurtle** [comment]
You can also try manually collapsing / uncollapsing / etc. the state of the notebook by going to the "commands" tab on the lhs of jupyterlab and play around with the various collapsible headers commands there to see if any of them do anything. I'm guessing they won't do anything, but can't hurt to try.

**Comment by aquirdTurtle** [comment]
Also, there was a similar problem being reported in [another issue](https://github.com/aquirdTurtle/Collapsible_Headings/issues/24) and in the main jupyterlab github as an [issue](https://github.com/jupyterlab/jupyterlab/issues/8122), and the user found that they needed to delete a specific file to get the extension to work:

`<conda_root>/envs/<env_name>/share/jupyter/lab/settings/build_config.json` or 
 `<conda_root>/share/jupyter/lab/settings/build_config.json`

So maybe try to find this file on your system and delete it?
