### ISSUE TITLE
Update for Jupyterlab 3.0

### ISSUE THREAD

**Issue by aquirdTurtle** [aquirdTurtle/Collapsible_Headings#30]
I expect to need to update the extension to make a version compatible with jupyterlab 3.0 as it comes out.

**Comment by ea42gh** [comment]
hope to see this soon! I use this all the time

**Comment by aquirdTurtle** [comment]
I've got version 3.0.0, compatible with jupyterlab 3.0, published on npm. Should be possible to update to this version using the jupyterlab package manager as was done before, I have yet to get this published on pypi or conda-forge, as the jupyterlab team recommends, so I'll have to work on that in the future. Please let me know if anyone runs into any issues with this! With changes to the jupyterlab packaging / build system I wouldn't be too surprised if there are still some quirks to work out.
