### ISSUE TITLE
Can't get it to work on jupyterlab 3.0.2

### ISSUE THREAD

**Issue by j0kaso** [aquirdTurtle/Collapsible_Headings#32]
Hi!

I tried to install it through pip, which worked but it is not working in the application. When I tried to install it through the Extension Manager, I get this problem:

```
Extension Installation Error
An error occurred installing @aquirdturtle/collapsible_headings.

Error message:

"@aquirdturtle/collapsible_headings" is not a valid npm package
```
Hope you can help!

**Comment by aquirdTurtle** [comment]
Hi @j0kaso, hmm, strange. With `npm`, I was running into some similar error messages in publishing my extension to npm, although after I managed to squirm around the errors I haven't been having trouble installing from the published version on my various devices. Maybe try updating nodejs? `conda update -c conda-forge nodejs`. I have less experience with using pip to install tbh. It sounds like pip reports that it installed successfully but that simply nothing shows up in jupyterlab? Can you trying to use the browser debugger tools (hit f12 in the browser) and see if there are any messages regarding the extension? You should see `JupyterLab extension @aquirdturtle/collapsible_headings is activated!!` in the console of the debugger. If none of these things gives an obvious solution, can you try making a fresh conda (or similar) environment and only installing jupyterlab and the extension? 

E.g. do the following in a prompt with admin priviledges (you may need to uninstall the pip version first `pip uninstall aquirdturtle_collapsible_headings`, not sure):

```
conda create -n myenv jupyterlab nodejs
conda activate myenv
jupyter lab
```

and then install the extension using the extension manager. You may want to make sure that jupyterlab >= 3.0.0 and nodejs >= 12 (my current versions which are working are 3.0.3 and 15.3.0 respectively). Let me know if any of these things helps.

**Comment by j0kaso** [comment]
Hi @aquirdTurtle, thanks for your quick reply.
Seems my problem is because I'm using a forwarding from a remote server. I did run it locally, could install it, and then started the automatic forwarding - seems there is an installation mismatch with nodejs on my side. Maybe not the best solution for how I circumvent it but it worked! Thanks again so much for your help!
