### ISSUE TITLE
Insert heading above or below

### ISSUE THREAD

**Issue by MaximLippeveld** [aquirdTurtle/Collapsible_Headings#5]
Hi!

Thanks for making this extension, I use it daily (in old notebooks mainly)!

I really like the shift-a/b shortcut present in the original notebook extension for inserting headers above or below the current one. Any plans on adding that to this extension?

Thanks.

**Comment by aquirdTurtle** [comment]
Hi @mlippie, thanks for the request. I've added these shortcuts to the most recent version of the extension, 0.4.2, just released. I tried to model the behavior of these commands to match the old nbextension as close as possible. Let me know if there are any problems.
