### ISSUE TITLE
Not working on Jupyterlab Version 1.1.1

### ISSUE THREAD

**Issue by lambdamusic** [aquirdTurtle/Collapsible_Headings#7]
I can't get it to work on Version 1.1.1

Installation seemed ok
```
>jupyter labextension install @aquirdturtle/collapsible_headings
Building jupyterlab assets (build:prod:minimize)
>
```
But then no noticeable difference in the UI. Maybe it needs to be turned on somewhere?

**Comment by lambdamusic** [comment]
Can confirm it works now.

I just had to restart the juplab server for the packages to complete
building, apparently.

So no issue here.tx!





----
Michele Pasin
http://www.michelepasin.org

**Comment by aquirdTurtle** [comment]
Thanks for the update. Will close unless there are further problems.
