### ISSUE TITLE
Use the keyboard arrows to close/open sections

### ISSUE THREAD

**Issue by Tabixe** [aquirdTurtle/Collapsible_Headings#8]
Hi aquirdTurtle,

Thanks a lot for your great extension!! Are you thinking in including in your extension the power of close and open the sections with the keyboard arrows? As it works with the NBextension on jupyter notebook.

Thanks,
Javi

**Comment by aquirdTurtle** [comment]
Hi @Tabixe, thanks for submitting the request. These shortcuts are now included in the most recent version `0.4.2`, just released. Let me know if there are any problems.

**Comment by Tabixe** [comment]
Hi @aquirdTurtle 

I just updated and it's great!! Thanks so much. However, I have to push my luck and ask you for more improvements:

**1.  Issue with the "down arrow":** currently the "down arrow" work as the "right arrrow" opening the sections when you overpass them. 
https://drive.google.com/file/d/1enm2zd83Frkg7V72vRnNPzhiqIrF4uKm/view?usp=sharing

**2. Issue with the "up arrow":** as the "down arrow" it also opens the sections when you overpass them.
https://drive.google.com/file/d/1WKNJ6ztjz6W_tf1Y9Ru3MIWeIBnozW25/view?usp=sharing

**3. Issue with the subsections:** when you are in a header of a subsection you are not able to go one level up by pressing the '"left arrow"
https://drive.google.com/file/d/1fVQ7YKtl-HoaJyZhDg9o8Nea1Zn27y4o/view?usp=sharing

**4. Issue with the relocation of the scroll bar:** when you close a really big section, the scroll bar doesn't get adjusted automatically making impossible see where are you.
https://drive.google.com/file/d/1NLMyBbn2ZX6APAxpDgNVHjbyIUsETdwg/view?usp=sharing

**Comment by aquirdTurtle** [comment]
Hi @Tabixe, thanks for enumerating these issues for me. I believe I've fixed 1, 2, and 3 in version 0.5.0, available now. See issue #10 for more info.
