### ISSUE TITLE
Collapsible headings not working with Jupyterlab 1.1 and 1.2

### ISSUE THREAD

**Issue by jbweston** [aquirdTurtle/Collapsible_Headings#9]
When using Collapsible_Headings with Jupyterlab 1.2.0 I do not see any of the UI elements for collapsing headings:

![2019-11-01-111259_633x252_scrot](https://user-images.githubusercontent.com/6654709/68018243-f78dba80-fc98-11e9-83ff-338e4527ade2.png)

Inspecting the javascript console gives some hints:

![2019-11-01-111316_554x124_scrot](https://user-images.githubusercontent.com/6654709/68018281-0aa08a80-fc99-11e9-8796-39b788c9739b.png)

The `cell.constructor.name` is seemingly `H` for all the markdown cells, but [this check](https://github.com/aquirdTurtle/Collapsible_Headings/blob/master/src/index.ts#L317) checks for `MarkdownCell` or `xe`.

In addition, despite the first 2 cells being header cells,  it seems that `selectedHeaderInfo.isHeader` is `false`.

**Comment by jbweston** [comment]
it seems that `getHeaderInfo` also checks for `cell.constructor.name` [here](https://github.com/aquirdTurtle/Collapsible_Headings/blob/master/src/index.ts#L513), so it is unsurprising that  `selectedHeaderInfo.isHeader` is `false`

**Comment by jbweston** [comment]
I see the same behaviour with Jupyterlab 1.1, except that the javascript console gives something slightly different:
![2019-11-01-161040_638x116_scrot](https://user-images.githubusercontent.com/6654709/68034567-2b310a80-fcc2-11e9-9f46-abe62f8e94d4.png)
Note the `z` in place of `H` and `p` in place of `B`

**Comment by aquirdTurtle** [comment]
Thanks for opening this issue. I should have realized checking the cell constructor name wasn't a good method for checking the cell type when I had to add "xe" for it to work on one of my computers. This should be fixed in version 0.5.0. Please let me know if there are any additional issues. Closing for now.
